// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CallPlugin(arg1:string,arg2:string,arg3:Array<any>):Promise<any>;

export function GetRegisteredPlugins():Promise<Array<string>>;

export function OnAppStarted():Promise<void>;
